import { CascadeSimulation } from '../core/cascade-core.js';

export class CascadeScene {
  constructor(canvas, ui) {
    this.canvas=canvas; this.ui=ui; const requestedSeed=Number(new URL(window.location.href).searchParams.get('seed')); this.seed=Number.isFinite(requestedSeed)&&requestedSeed>0?Math.floor(requestedSeed):48152;
    this.tuning={cohesion:1,speed:1,friction:1,light:.82};
    this.sim=new CascadeSimulation({size:64,cellSize:1.25,seed:this.seed});
    this.engine=new BABYLON.Engine(canvas,true,{preserveDrawingBuffer:true,stencil:true});
    this.scene=new BABYLON.Scene(this.engine); this.scene.clearColor=new BABYLON.Color4(.12,.12,.19,1);
    this.aimPoint=null; this.shotFired=false; this.accumulator=0; this.damage=0; this.finished=false;
    this.buildScene(); this.bindInput(); this.ui.setSeed(this.seed);
    this.engine.runRenderLoop(()=>this.frame()); window.addEventListener('resize',()=>this.engine.resize());
  }

  buildScene(){
    const s=this.scene; s.fogMode=BABYLON.Scene.FOGMODE_EXP2; s.fogDensity=.0042; s.fogColor=new BABYLON.Color3(.66,.55,.66);
    s.imageProcessingConfiguration.contrast=1.18; s.imageProcessingConfiguration.exposure=1.08;
    this.hemi=new BABYLON.HemisphericLight('sky',new BABYLON.Vector3(-.4,1,-.2),s); this.hemi.intensity=.72; this.hemi.diffuse=new BABYLON.Color3(.56,.65,.9); this.hemi.groundColor=new BABYLON.Color3(.22,.14,.25);
    this.sun=new BABYLON.DirectionalLight('sun',new BABYLON.Vector3(-.72,-.42,.3),s); this.sun.position=new BABYLON.Vector3(48,38,-55); this.sun.intensity=2.65; this.sun.diffuse=new BABYLON.Color3(1,.56,.32); this.sun.specular=new BABYLON.Color3(1,.68,.46);
    this.camera=new BABYLON.ArcRotateCamera('camera',-Math.PI/2,1.08,92,new BABYLON.Vector3(0,13,7),s); this.camera.lowerRadiusLimit=48;this.camera.upperRadiusLimit=125;this.camera.lowerBetaLimit=.55;this.camera.upperBetaLimit=1.42;this.camera.wheelPrecision=35;this.camera.pinchPrecision=80;this.camera.attachControl(this.canvas,true);
    this.createBackdrop(); this.mountain=this.createMountainMesh(); this.snowMesh=this.createSnowMassMesh(); this.createTrees(); this.createTargets(); this.createCannon();
  }

  clayMaterial(name,color,rough=.95){const m=new BABYLON.PBRMaterial(name,this.scene);m.albedoColor=color;m.roughness=rough;m.metallic=0;m.environmentIntensity=.35;return m;}
  createBackdrop(){const disc=BABYLON.MeshBuilder.CreateDisc('sunDisc',{radius:9,tessellation:48},this.scene);disc.position.set(34,34,38);disc.rotation.y=Math.PI;const mat=new BABYLON.StandardMaterial('sunDiscMat',this.scene);mat.emissiveColor=new BABYLON.Color3(1,.34,.18);mat.disableLighting=true;disc.material=mat;disc.isPickable=false;}

  createMountainMesh(){
    const s=this.sim.size,cs=this.sim.cellSize,positions=[],indices=[],normals=[],colors=[];
    for(let z=0;z<s;z++)for(let x=0;x<s;x++){const i=this.sim.index(x,z);positions.push((x-s/2)*cs,this.sim.height[i],(z-s/2)*cs);const snow=Math.min(1,this.sim.snow[i]/2.4);const variation=((x*17+z*11)%13)/13;colors.push(.34+snow*.53+variation*.025,.27+snow*.61+variation*.018,.32+snow*.64,1);}
    for(let z=0;z<s-1;z++)for(let x=0;x<s-1;x++){const i=z*s+x,r=i+1,d=i+s,dr=d+1;indices.push(i,d,r,r,d,dr);}
    BABYLON.VertexData.ComputeNormals(positions,indices,normals);const vd=new BABYLON.VertexData();vd.positions=positions;vd.indices=indices;vd.normals=normals;vd.colors=colors;
    const mesh=new BABYLON.Mesh('mountain',this.scene);vd.applyToMesh(mesh,true);const mat=this.clayMaterial('mountainClay',BABYLON.Color3.White(),1);mat.backFaceCulling=false;mesh.material=mat;mesh.isPickable=true;return mesh;
  }
  createSnowMassMesh(){const mesh=BABYLON.MeshBuilder.CreateIcoSphere('movingSnow',{radius:.42,subdivisions:1},this.scene);mesh.material=this.clayMaterial('snowClay',new BABYLON.Color3(.96,.88,.91),.98);mesh.isPickable=false;mesh.thinInstanceEnablePicking=false;return mesh;}
  createTrees(){this.treeMeshes=[];const trunkMat=this.clayMaterial('trunkClay',new BABYLON.Color3(.28,.13,.16));const pineMat=this.clayMaterial('pineClay',new BABYLON.Color3(.12,.24,.25));for(let n=0;n<75;n++){const x=-34+((n*19)%69),z=-30+((n*31)%56);if(z>15||Math.abs(x)<6&&z>-4)continue;const y=this.sim.sampleWorldHeight(x,z);const trunk=BABYLON.MeshBuilder.CreateCylinder(`trunk${n}`,{height:1.8,diameter:.42,tessellation:7},this.scene);trunk.position.set(x,y+.9,z);trunk.material=trunkMat;const crown=BABYLON.MeshBuilder.CreateCylinder(`pine${n}`,{height:3.8,diameterTop:.15,diameterBottom:2.1,tessellation:8},this.scene);crown.position.set(x,y+3,z);crown.scaling.x=.84+((n%5)*.035);crown.rotation.y=(n%8)*.21;crown.material=pineMat;this.treeMeshes.push(trunk,crown);}}
  createTargets(){this.targets=[];const defs=[{x:-10,z:-22,label:'CHALET',value:1800},{x:-2,z:-25,label:'LODGE',value:3200},{x:9,z:-19,label:'LIFT',value:2200},{x:15,z:-27,label:'BRIDGE',value:4200}];const wall=this.clayMaterial('targetClay',new BABYLON.Color3(.62,.22,.16));const roof=this.clayMaterial('roofClay',new BABYLON.Color3(.23,.11,.18));for(const d of defs){const y=this.sim.sampleWorldHeight(d.x,d.z)+1;const mesh=BABYLON.MeshBuilder.CreateBox(d.label,{width:3.2,height:2,depth:3.2},this.scene);mesh.position.set(d.x,y,d.z);mesh.rotation.y=((d.x+d.z)%7)*.04;mesh.material=wall;const cap=BABYLON.MeshBuilder.CreateCylinder(`${d.label}Roof`,{height:1.4,diameter:4.5,tessellation:4},this.scene);cap.position.set(d.x,y+1.55,d.z);cap.rotation.y=Math.PI/4;cap.material=roof;cap.parent=mesh;cap.position.set(0,1.55,0);this.targets.push({...d,mesh,destroyed:false});}}
  createCannon(){const mat=this.clayMaterial('cannonClay',new BABYLON.Color3(.16,.19,.22));const base=BABYLON.MeshBuilder.CreateCylinder('cannonBase',{diameter:4,height:1.2,tessellation:10},this.scene);base.position.set(-28,2,-31);base.material=mat;const barrel=BABYLON.MeshBuilder.CreateCylinder('barrel',{diameter:1.1,height:8,tessellation:9},this.scene);barrel.rotation.x=Math.PI/2;barrel.rotation.z=-.18;barrel.position.set(-26.7,4.2,-27.5);barrel.material=mat;}
  bindInput(){this.scene.onPointerObservable.add(info=>{if(this.shotFired||info.type!==BABYLON.PointerEventTypes.POINTERPICK)return;const p=info.pickInfo;if(p?.hit&&p.pickedMesh===this.mountain){this.aimPoint=p.pickedPoint.clone();this.ui.showReticle(this.scene,this.camera,this.aimPoint);this.ui.setShot('AIM LOCKED');}});}
  setTuning(key,value){this.tuning[key]=value;if(key==='light'){this.sun.intensity=1.4+value*1.7;this.hemi.intensity=.45+value*.34;this.scene.fogColor=new BABYLON.Color3(.45+value*.25,.42+value*.17,.58+value*.12);}}
  fire(){if(!this.aimPoint||this.shotFired)return;this.shotFired=true;this.ui.setShot('IN FLIGHT');this.ui.disableFire(true);const shell=BABYLON.MeshBuilder.CreateIcoSphere('shell',{radius:.34,subdivisions:1},this.scene);const mat=new BABYLON.StandardMaterial('shellMat',this.scene);mat.emissiveColor=new BABYLON.Color3(1,.35,.08);shell.material=mat;const start=new BABYLON.Vector3(-25,5,-26);shell.position.copyFrom(start);const target=this.aimPoint.clone(),duration=900,began=performance.now();const animate=()=>{const t=Math.min(1,(performance.now()-began)/duration);BABYLON.Vector3.LerpToRef(start,target,t,shell.position);shell.position.y+=Math.sin(Math.PI*t)*13;if(t<1)requestAnimationFrame(animate);else{shell.dispose();this.impact(target);}};animate();}
  impact(point){this.ui.setShot('IMPACT');const flash=BABYLON.MeshBuilder.CreateIcoSphere('impactFlash',{radius:.7,subdivisions:1},this.scene);flash.position.copyFrom(point);const mat=new BABYLON.StandardMaterial('flashMat',this.scene);mat.emissiveColor=new BABYLON.Color3(1,.52,.18);flash.material=mat;const start=performance.now(),pulse=()=>{const t=(performance.now()-start)/350;flash.scaling.setAll(1+t*8);mat.alpha=1-t;if(t<1)requestAnimationFrame(pulse);else flash.dispose();};pulse();const triggered=this.sim.triggerAt(point.x,point.z,1/this.tuning.cohesion);this.ui.setShot(triggered?'FRACTURE':'NO RELEASE');if(!triggered)setTimeout(()=>this.finish(),1200);}
  frame(){const dt=Math.min(.05,this.engine.getDeltaTime()/1000);this.ui.setFps(this.engine.getFps());if(this.shotFired&&this.sim.active){this.accumulator+=dt*this.tuning.speed;while(this.accumulator>=this.sim.fixedDt){this.sim.flowScale=this.tuning.speed;this.sim.frictionScale=this.tuning.friction;this.sim.step();this.accumulator-=this.sim.fixedDt;}this.updateSnowInstances();this.updateTargets();this.ui.update(this.sim.totalReleased*1.7,this.damage);if(!this.sim.active)this.finish();}this.scene.render();if(this.aimPoint&&!this.shotFired)this.ui.showReticle(this.scene,this.camera,this.aimPoint);}
  updateSnowInstances(){const matrices=[],m=BABYLON.Matrix.Identity(),scale=new BABYLON.Vector3(),q=BABYLON.Quaternion.Identity(),pos=new BABYLON.Vector3(),stride=this.sim.totalReleased>150?2:1;for(let z=0;z<this.sim.size;z+=stride)for(let x=0;x<this.sim.size;x+=stride){const i=this.sim.index(x,z),mass=this.sim.moving[i];if(mass<.025)continue;const p=this.sim.worldPosition(x,z);pos.set(p.x,p.y+.22,p.z);const sz=.5+Math.min(2.6,Math.sqrt(mass)*1.7);scale.set(sz,.45+sz*.18,sz);BABYLON.Matrix.ComposeToRef(scale,q,pos,m);matrices.push(...m.toArray());}this.snowMesh.thinInstanceSetBuffer('matrix',new Float32Array(matrices),16,true);}
  updateTargets(){for(const t of this.targets){if(t.destroyed)continue;const gx=Math.round(t.x/this.sim.cellSize+this.sim.size/2),gz=Math.round(t.z/this.sim.cellSize+this.sim.size/2);let force=0;for(let dz=-2;dz<=2;dz++)for(let dx=-2;dx<=2;dx++)if(this.sim.inBounds(gx+dx,gz+dz))force+=this.sim.moving[this.sim.index(gx+dx,gz+dz)];if(force>2.4){t.destroyed=true;this.damage+=t.value;t.mesh.rotation.z=.95;t.mesh.position.y-=.7;t.mesh.scaling.y=.45;}}}
  finish(){if(this.finished)return;this.finished=true;this.ui.setShot('SETTLED');const title=this.damage>=7000?'PERFECT CASCADE':this.damage>=3000?'CHAIN REACTION':this.damage>0?'PARTIAL RELEASE':'THE MOUNTAIN HELD';setTimeout(()=>this.ui.showResult(title),700);}
  reset(){window.location.reload();}
  reseed(){const u=new URL(window.location.href);u.searchParams.set('seed',String(Math.floor(10000+Math.random()*89999)));window.location.href=u.toString();}
}
