import { CascadeScene } from './game/scene.js';
const $=id=>document.getElementById(id);
const ui={setShot:v=>$('shotState').textContent=v,update:(mass,damage)=>{$('releasedMass').textContent=`${Math.round(mass).toLocaleString()} t`;$('damageScore').textContent=damage.toLocaleString();},disableFire:v=>$('fireButton').disabled=v,showResult:title=>{$('resultTitle').textContent=title;$('resultPanel').hidden=false;},showReticle:(scene,camera,point)=>{const p=BABYLON.Vector3.Project(point,BABYLON.Matrix.Identity(),scene.getTransformMatrix(),camera.viewport.toGlobal(scene.getEngine().getRenderWidth(),scene.getEngine().getRenderHeight()));const r=$('reticle');r.style.display='block';r.style.left=`${p.x}px`;r.style.top=`${p.y}px`;},setSeed:seed=>$('seedValue').textContent=seed,setFps:fps=>$('fpsValue').textContent=Math.round(fps),setFracture:(cells,mass)=>{$('fractureState').textContent=cells?`${cells} cells · ${Math.round(mass)} t`:'—';},setCamera:value=>$('cameraState').textContent=value};
const game=new CascadeScene($('renderCanvas'),ui);
$('buildVersion').textContent='v0.4.3';
const hud=$('hud'),header=hud.querySelector('header'),statusPanel=document.createElement('div'),statusToggle=document.createElement('button');statusPanel.id='statusPanel';statusPanel.hidden=true;statusPanel.append($('readout'),$('buildHud'));statusToggle.id='statusToggle';statusToggle.type='button';statusToggle.setAttribute('aria-expanded','false');statusToggle.setAttribute('aria-controls','statusPanel');statusToggle.innerHTML='<span>STATUS</span><b>＋</b>';header.after(statusToggle,statusPanel);const setStatus=open=>{statusPanel.hidden=!open;statusToggle.setAttribute('aria-expanded',String(open));statusToggle.querySelector('b').textContent=open?'−':'＋';};statusToggle.addEventListener('click',()=>setStatus(statusPanel.hidden));
const scene=game.scene;scene.clearColor=new BABYLON.Color4(.64,.56,.7,1);scene.fogColor=new BABYLON.Color3(.64,.55,.68);scene.fogDensity=.0027;scene.ambientColor=new BABYLON.Color3(.2,.17,.23);scene.imageProcessingConfiguration.contrast=1.08;scene.imageProcessingConfiguration.exposure=1.12;if(game.hemi){game.hemi.intensity=.72;game.hemi.diffuse=new BABYLON.Color3(.72,.68,.86);game.hemi.groundColor=new BABYLON.Color3(.38,.29,.42);}if(game.sun){game.sun.intensity=2.15;game.sun.diffuse=new BABYLON.Color3(1,.69,.48);}if(game.shadowGenerator){game.shadowGenerator.setDarkness(.18);game.shadowGenerator.blurKernel=38;}const sunsetSvg=`<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#7776a3"/><stop offset="0.5" stop-color="#bc8294"/><stop offset="0.78" stop-color="#e9a174"/><stop offset="1" stop-color="#f4c497"/></linearGradient></defs><rect width="16" height="16" fill="url(#g)"/></svg>`;new BABYLON.Layer('sunsetGradient',`data:image/svg+xml,${encodeURIComponent(sunsetSvg)}`,scene,true);
$('fireButton').addEventListener('click',()=>game.fire());$('resetButton').addEventListener('click',()=>game.reset());$('retryButton').addEventListener('click',()=>game.reset());$('reseedButton').addEventListener('click',()=>game.reseed());
const panel=$('tuningPanel'),toggle=$('tuneToggle'),setPanel=open=>{panel.hidden=!open;toggle.setAttribute('aria-expanded',String(open));};toggle.addEventListener('click',()=>setPanel(panel.hidden));$('closeTune').addEventListener('click',()=>setPanel(false));
for(const id of ['cohesion','speed','friction','light','fractureRadius','stressDecay','continuity','releaseDepth','terrainResistance','coreDensity','lateralSpread','momentum','entrainment','powder','deposition','camera']){const input=$(id),out=$(`${id}Out`);input.addEventListener('input',()=>{const value=Number(input.value);out.value=value.toFixed(2);game.setTuning(id,value);});}