import { CascadeScene } from './game/scene.js';
import './game/deformable-snowpack-v060.js';
import './game/continuous-flow-surface-v070.js';
import './game/leading-edge-mist-v072.js';
import './game/continuous-surface-polish-v075.js';
const $=id=>document.getElementById(id);
const ui={setShot:v=>$('shotState').textContent=v,update:(mass,damage)=>{$('releasedMass').textContent=`${Math.round(mass).toLocaleString()} t`;$('damageScore').textContent=damage.toLocaleString();},disableFire:v=>$('fireButton').disabled=v,showResult:title=>{$('resultTitle').textContent=title;$('resultPanel').hidden=false;},showReticle:(scene,camera,point)=>{const p=BABYLON.Vector3.Project(point,BABYLON.Matrix.Identity(),scene.getTransformMatrix(),camera.viewport.toGlobal(scene.getEngine().getRenderWidth(),scene.getEngine().getRenderHeight()));const r=$('reticle');r.style.display='block';r.style.left=`${p.x}px`;r.style.top=`${p.y}px`;},setSeed:seed=>$('seedValue').textContent=seed,setFps:fps=>$('fpsValue').textContent=Math.round(fps),setFracture:(cells,mass)=>{$('fractureState').textContent=cells?`${cells} cells · ${Math.round(mass)} t`:'—';},setCamera:value=>$('cameraState').textContent=value};
$('buildVersion').textContent='v0.7.5-surface-polish';
const game=new CascadeScene($('renderCanvas'),ui);
$('fireButton').addEventListener('click',()=>game.fire());$('resetButton').addEventListener('click',()=>game.reset());$('retryButton').addEventListener('click',()=>game.reset());$('reseedButton').addEventListener('click',()=>game.reseed());
const panel=$('tuningPanel'),toggle=$('tuneToggle'),setPanel=open=>{panel.hidden=!open;toggle.setAttribute('aria-expanded',String(open));};toggle.addEventListener('click',()=>setPanel(panel.hidden));$('closeTune').addEventListener('click',()=>setPanel(false));
const status=$('statusPanel'),statusToggle=$('statusToggle'),setStatus=open=>{status.hidden=!open;statusToggle.setAttribute('aria-expanded',String(open));statusToggle.querySelector('b').textContent=open?'−':'+';};statusToggle.addEventListener('click',()=>setStatus(status.hidden));
for(const id of ['cohesion','speed','friction','light','fractureRadius','stressDecay','continuity','releaseDepth','terrainResistance','coreDensity','lateralSpread','momentum','entrainment','powder','deposition','camera']){const input=$(id),out=$(`${id}Out`);input.addEventListener('input',()=>{const value=Number(input.value);out.value=value.toFixed(2);game.setTuning(id,value);});}